name: app_doc_sach
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_nav_bar: ^5.0.6
  badges: ^3.1.2
  http: ^1.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_auth: ^4.19.1
  sign_in_button: ^3.2.0
  shared_preferences: ^2.2.3
  flutter_switch: ^0.3.2
  day_night_themed_switch: ^1.0.0
  flutter_statusbarcolor_ns: ^0.5.0
  firebase_database: ^10.5.2
  progress_dialog_null_safe: ^3.0.0
  restart_app: ^1.2.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.4
  flutter_easyloading: ^3.0.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  autocomplete_textfield: ^2.0.1
  flutter_typeahead: ^5.0.1
  firebase_core: ^2.29.0
  fl_chart: ^0.68.0
  flutter_svg: ^2.0.5
  country_picker: ^2.0.26
  country_icons: ^2.0.0
  image_picker: ^0.8.4+3
  universal_io: ^2.0.4
  flutter_cache_manager: ^3.3.2
  http_parser: ^4.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  intl: ^0.19.0
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon/logoapp.png"
    min_sdk_android: 21
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/icon/
    - assets/book/
    - assets/images/avatar.png
    - assets/placeholder.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
